<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-04-19 23:25
=======
# Generated by Django 4.0.3 on 2022-04-15 20:32
>>>>>>> e93ebd5 (get all from lesson_6)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='имя')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
        ),
    ]
